# -*- coding: utf-8 -*-
"""ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sDgHFUVHWH_gMqlyeAPJmJ_lQNOK3-om
"""

# 1.	Write a Program to interchange first and last elements in a list

def swap_list(new_list):
  size = len(new_list)

  # Swapping
  temp = new_list[0]
  new_list[0] = new_list[size - 1]
  new_list[size - 1] = temp

  return new_list

newList = [12, 35, 9, 56, 24]

print(swap_list(newList))

#  2.	Program to swap two elements in a list

def swap_positions(list, pos1, pos2):

    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list

List = [23, 65, 19, 90]
pos1, pos2  = 1, 3

print(swap_positions(List, pos1-1, pos2-1))

# 3.	Swap elements in String list

def swap_string_list_elements(str_list, pos1, pos2):

  str_list[pos1], str_list[pos2] = str_list[pos2], str_list[pos1]
  return str_list

# Example usage:
string_list = ["apple", "banana", "cherry", "date"]
pos1 = 0
pos2 = 2

new_string_list = swap_string_list_elements(string_list, pos1, pos2)
print(new_string_list)

# 4. Ways to find length of list

# len() function
my_list = [1, 2, 3, 4, 5]
list_length = len(my_list)
print("Length of the list ", list_length)

#5.	Maximum of two numbers in Python

def max_of_two(x, y):
  if x > y:
    return x
  return y


num1 = 10
num2 = 14

print("Maximum of two numbers is: ", max_of_two(num1, num2))

# 6. MINIMUM of two numbers in Python

def min_of_two(x, y):
  if x < y:
    return x
  return y


num1 = 10
num2 = 14

print("Minimum of two numbers is: ", min_of_two(num1, num2))

# 7.	Ways to check if element exists in list

my_list = [1, 2, 3, 4, 5]
element_to_check = 3

if element_to_check in my_list:
  print(f"{element_to_check} exists in the list.")
else:
  print(f"{element_to_check} does not exist in the list.")

#8.	Different ways to clear a list in Python

my_list = [1, 2, 3, 4, 5]
my_list.clear()
print("List after clearing using clear():", my_list)

# 9.	Reversing a List

def reverse_list(input_list):
  reversed_list = input_list[::-1]
  return reversed_list

my_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(my_list)
print("Reversed list:", reversed_list)

#10.	Cloning or Copying a list

def clone_list(input_list):
  cloned_list = input_list.copy()
  return cloned_list
my_list = [1, 2, 3, 4, 5]
cloned_list = clone_list(my_list)

print("Original list:", my_list)
print("Cloned list:", cloned_list)

# 11.	Count occurrences of an element in a list

def count_occurrences(input_list, element):

  count = input_list.count(element)
  return count


# Example usage:
my_list = [1, 2, 3, 4, 2, 2, 5, 2]
element_to_count = 2

occurrences = count_occurrences(my_list, element_to_count)
print(f"The element {element_to_count} appears {occurrences} times in the list.")

# 12.	Program to find sum and average of List in Python

def sum_and_average_of_list(input_list):


  if not input_list:
    return 0, 0  # Return 0 for both sum and average if the list is empty

  list_sum = sum(input_list)
  list_average = list_sum / len(input_list)
  return list_sum, list_average


# Example usage:
my_list = [1, 2, 3, 4, 5]
list_sum, list_average = sum_and_average_of_list(my_list)

# 13.	Sum of number digits in List

def sum_of_digits_in_list(input_list):
  total_sum = 0
  for num in input_list:
    for digit in str(num):
      total_sum += int(digit)
  return total_sum

my_list = [12, 34, 56]
sum_of_digits = sum_of_digits_in_list(my_list)
print("Sum of digits in the list:", sum_of_digits)


# 14.	Multiply all numbers in the list

def multiply_list_numbers(input_list):
  product = 1
  for num in input_list:
    product *= num
  return product

my_list = [1, 2, 3, 4, 5]
product_of_numbers = multiply_list_numbers(my_list)
print("Product of numbers in the list:", product_of_numbers)

# 15.	Program to find smallest number in a list

def find_smallest_number(input_list):
  if not input_list:
    return None
  smallest_number = input_list[0]
  for num in input_list:
    if num < smallest_number:
      smallest_number = num
  return smallest_number

my_list = [12, 34, 5, 6, 7]
smallest_number = find_smallest_number(my_list)
print("Smallest number in the list:", smallest_number)


# 16.	Program to find largest number in a list

def find_largest_number(input_list):
  if not input_list:
    return None
  largest_number = input_list[0]
  for num in input_list:
    if num > largest_number:
      largest_number = num
  return largest_number

my_list = [12, 34, 5, 6, 7, 100]
largest_number = find_largest_number(my_list)
print("Largest number in the list:", largest_number)


# 17.	Program to find second largest number in a list

def find_second_largest_number(input_list):
  if len(input_list) < 2:
    return None

  largest = float('-inf')
  second_largest = float('-inf')

  for num in input_list:
    if num > largest:
      second_largest = largest
      largest = num
    elif num > second_largest and num != largest:
      second_largest = num

  if second_largest == float('-inf'):
    return None

  return second_largest

my_list = [12, 34, 5, 6, 7, 100, 90]
second_largest_number = find_second_largest_number(my_list)
print("Second largest number in the list:", second_largest_number)


# 18.	Program to print even numbers in a list

def print_even_numbers(input_list):
  for num in input_list:
    if num % 2 == 0:
      print(num)

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Even numbers in the list:")
print_even_numbers(my_list)


# 19.	Program to print odd numbers in a List

def print_odd_numbers(input_list):
  for num in input_list:
    if num % 2 != 0:
      print(num)

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Odd numbers in the list:")
print_odd_numbers(my_list)


# 20.	Program to print all even numbers in a range

def print_even_numbers_in_range(start, end):
  for num in range(start, end + 1):
    if num % 2 == 0:
      print(num)

start_range = 1
end_range = 10
print("Even numbers in the range:")
print_even_numbers_in_range(start_range, end_range)

# 21.	Program to print all odd numbers in a range

def print_odd_numbers_in_range(start, end):
  for num in range(start, end + 1):
    if num % 2 != 0:
      print(num)

start_range = 1
end_range = 10
print("Odd numbers in the range:")
print_odd_numbers_in_range(start_range, end_range)

# 22.	Program to count Even and Odd numbers in a List

def count_even_odd(input_list):
  even_count = 0
  odd_count = 0
  for num in input_list:
    if num % 2 == 0:
      even_count += 1
    else:
      odd_count += 1
  return even_count, odd_count


my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_count, odd_count = count_even_odd(my_list)
print("Number of even numbers:", even_count)
print("Number of odd numbers:", odd_count)


# 23.	Program to print positive numbers in a list

def print_positive_numbers(input_list):
  for num in input_list:
    if num > 0:
      print(num)


my_list = [-1, 2, -3, 4, -5, 6]
print("Positive numbers in the list:")
print_positive_numbers(my_list)


# 24.	Program to print negative numbers in a list

def print_negative_numbers(input_list):
  for num in input_list:
    if num < 0:
      print(num)


my_list = [-1, 2, -3, 4, -5, 6]
print("Negative numbers in the list:")
print_negative_numbers(my_list)


# 25.	Program to print all positive numbers in a range

def print_positive_numbers_in_range(start, end):
  for num in range(start, end + 1):
    if num > 0:
      print(num)


start_range = -5
end_range = 5
print("Positive numbers in the range:")
print_positive_numbers_in_range(start_range, end_range)


# 26.	Program to print all negative numbers in a range

def print_negative_numbers_in_range(start, end):
  for num in range(start, end + 1):
    if num < 0:
      print(num)


start_range = -5
end_range = 5
print("Negative numbers in the range:")
print_negative_numbers_in_range(start_range, end_range)


# 27.	Program to count positive and negative numbers in a list

def count_positive_negative(input_list):
  positive_count = 0
  negative_count = 0
  for num in input_list:
    if num > 0:
      positive_count += 1
    elif num < 0:
      negative_count += 1
  return positive_count, negative_count


my_list = [-1, 2, -3, 4, -5, 6]
positive_count, negative_count = count_positive_negative(my_list)
print("Number of positive numbers:", positive_count)
print("Number of negative numbers:", negative_count)


# 28.	Remove multiple elements from a list

def remove_multiple_elements(input_list, elements_to_remove):
  for element in elements_to_remove:
    while element in input_list:
      input_list.remove(element)
  return input_list

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
elements_to_remove = [2, 4, 6, 8, 10]
new_list = remove_multiple_elements(my_list, elements_to_remove)
print("List after removing elements:", new_list)

# 29.	Remove empty tuples from a list

def remove_empty_tuples(input_list):
  new_list = [tuple for tuple in input_list if tuple]
  return new_list

my_list = [(), (1, 2), (), (3,), ()]
new_list = remove_empty_tuples(my_list)
print("List after removing empty tuples:", new_list)

# 30.	Program to print duplicates from a list of integers

def print_duplicates(input_list):
  seen = set()
  duplicates = set()
  for num in input_list:
    if num in seen:
      duplicates.add(num)
    else:
      seen.add(num)
  print("Duplicate elements in the list:", list(duplicates))

my_list = [1, 2, 3, 4, 2, 5, 6, 3, 7, 8, 2]
print_duplicates(my_list)